routes/web.php
<?php

use App\Http\Controllers\Blog\PostsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('blog/posts/{post}', [PostsController::class, 'show'])->name('blog.show');
Route::get('blog/categories/{category}', [PostsController::class, 'category'])->name('blog.category');
Route::get('blog/tags/{tag}', [PostsController::class, 'tag'])->name('blog.tag');

Auth::routes();

Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'CategoriesController');
    
    Route::resource('tags', 'TagsController');

    Route::resource('posts', 'PostController')->middleware('auth');

    Route::get('trashed-posts', 'PostController@trashed')->name('trashed-posts.index');

    Route::put('restore-post/{post}', 'PostController@restore')->name('restore-posts');
    
});



    
Route::middleware(['admin', 'auth'])->group(function ()
{
    Route::get('users', 'UsersController@index' )->name('users.index');
    
    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');

    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');

    Route::put('users/profile', 'UsersController@update')->name('users.update-profile');

});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
    protected $fillable = ['name'];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Tag;
use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('tags.index')->with('tags', Tag::all());
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:tags'
        ]);

        $nTag = new Tag();

        Tag::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'Tag created successfully.');

        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tags.create')->with('tag', $tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request,Tag $tag)
    {
        
        $tag->update([
            'name' => $request->name
        ]);

        
        session()->flash('success', 'Tag updated successfully.');

        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        if ($tag->posts->count() > 0 ) {
            session()->flash('error' , 'Tag cannot be deleted. because it is associated to some posts.');

            return redirect()->back();
        }
	    $tag->delete();

        session()->flash('success', 'Tag deleted successfully.');

	    return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')


@section('content')

<div class="card card-default">
    <div class="card-header">
        {{ isset($tag) ? 'Edit Tag' : 'Create Tag' }} 
    </div>
    <div class="card-body">
       @include('partials.error')
        <form action="{{ isset($tag) ? route('tags.update', $tag->id) : route('tags.store') }} " method="POST">
            @csrf
            @if (isset($tag))
                @method('PUT')
            @endif
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" class="form-control" name="name" value="{{ isset($tag) ? $tag->name : '' }}">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                  {{ isset($tag) ? 'Update Tag' : 'Add Tag'}}  
                </button>
            </div>
        </form>
    </div>
</div>
    
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')


@section('content')

<div class="d-flex justify-content-end mb-2 ">
    <a href="{{ route('tags.create') }}" class="btn btn-success">Add Tag</a>
</div>

<div class="card card-default">
    <div class="card-header">
      Tags
    </div>
    <div class="card-body">
      @if($tags->count() > 0)
        <table class="table">
            <thead>
                <th>Name</th>
                <th>Posts count</th>
                <th></th>
            </thead>
            <tbody>
                @foreach ($tags as $tag)
                    <tr>
                        <td>
                            {{ $tag->name }}
                        </td>
                        <td>
                          {{ $tag->posts->count() }}
                        </td>
                        <td>
                            <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-info btn-sm">
                                Edit
                            </a>

                            <button class="btn btn-danger btn-sm" onclick="handleDelete({{ $tag->id }})">Delete</button>
			
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        
<!-- Modal -->
<form action="" method="post" id="deleteTagForm">
  @csrf
  @method('DELETE')
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Tag</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="text-center text-bold">
          Are you  sure you want to delete this tag?
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go back</button>
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
      </div>
    </div>
  </div>
</div>
</form>
      @else 
        <h3 class="text-center">No Tags Yet.</h3>
      @endif

    </div>
</div>

@section('scripts')
<script>
  function handleDelete(id) {
    var form = document.getElementById('deleteTagForm')
    form.action = '/tags/' + id
    $('#deleteModal').modal('show')
  }
</script>
@endsection
    
@endsection