routes/web.php
<?php

use App\Http\Controllers\Blog\PostsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('blog/posts/{post}', [PostsController::class, 'show'])->name('blog.show');
Route::get('blog/categories/{category}', [PostsController::class, 'category'])->name('blog.category');
Route::get('blog/tags/{tag}', [PostsController::class, 'tag'])->name('blog.tag');

Auth::routes();

Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'CategoriesController');
    
    Route::resource('tags', 'TagsController');

    Route::resource('posts', 'PostController')->middleware('auth');

    Route::get('trashed-posts', 'PostController@trashed')->name('trashed-posts.index');

    Route::put('restore-post/{post}', 'PostController@restore')->name('restore-posts');
    
});



    
Route::middleware(['admin', 'auth'])->group(function ()
{
    Route::get('users', 'UsersController@index' )->name('users.index');
    
    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');

    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');

    Route::put('users/profile', 'UsersController@update')->name('users.update-profile');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];


    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Category;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoriesRequest;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('categories.index')->with('categories', Category::all());
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:categories'
        ]);

        $ncategory = new Category();

        Category::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'Category created successfully.');

        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories.create')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoriesRequest $request,Category $category)
    {
        
        $category->update([
            'name' => $request->name
        ]);

        
        session()->flash('success', 'Category updated successfully.');

        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {

        if ($category->posts->count() > 0 ) {
            session()->flash('error' , 'Category cannot be deleted because it has some posts.');

            return redirect()->back();
        }


	    $category->delete();

        session()->flash('success', 'Category deleted successfully.');

	    return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')


@section('content')

<div class="card card-default">
    <div class="card-header">
        {{ isset($category) ? 'Edit Category' : 'Create Category' }} 
    </div>
    <div class="card-body">

        @include('partials.error')
        <form action="{{ isset($category) ? route('categories.update', $category->id) : route('categories.store') }} " method="POST">
            @csrf
            @if (isset($category))
                @method('PUT')
            @endif
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" class="form-control" name="name" value="{{ isset($category) ? $category->name : '' }}">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                  {{ isset($category) ? 'Update Category' : 'Add category'}}  
                </button>
            </div>
        </form>
    </div>
</div>
    
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')


@section('content')

<div class="d-flex justify-content-end mb-2 ">
    <a href="{{ route('categories.create') }}" class="btn btn-success">Add Category</a>
</div>

<div class="card card-default">
    <div class="card-header">
        Categories
    </div>
    <div class="card-body">
      @if($categories->count() > 0)
        <table class="table">
            <thead>
                <th>Name</th>
                <th>Posts count</th>
                <th></th>
            </thead>
            <tbody>
                @foreach ($categories as $categorie)
                    <tr>
                        <td>
                            {{ $categorie->name }}
                        </td>
                        <td>
                            {{ $categorie->posts->count() }}
                        </td>
                        <td>
                            <a href="{{ route('categories.edit', $categorie->id) }}" class="btn btn-info btn-sm">
                                Edit
                            </a>

                            <button class="btn btn-danger btn-sm" onclick="handleDelete({{ $categorie->id }})">Delete</button>
			
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        
<!-- Modal -->
<form action="" method="post" id="deleteCategoryForm">
  @csrf
  @method('DELETE')
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="text-center text-bold">
          Are you  sure you want to delete this category ?
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go back</button>
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
      </div>
    </div>
  </div>
</div>
</form>
      @else 
        <h3 class="text-center">No Categories Yet.</h3>
      @endif

    </div>
</div>

@section('scripts')
<script>
  function handleDelete(id) {
    var form = document.getElementById('deleteCategoryForm')
    form.action = '/categories/' + id
    $('#deleteModal').modal('show')
  }
</script>
@endsection
    
@endsection